# Generated by Django 5.0 on 2023-12-28 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
    ]
