# Generated by Django 5.0 on 2023-12-30 21:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronet', '0003_alter_company_distributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 31, 0, 7, 54, 698018), null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='company',
            name='distributor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='electronet.company', verbose_name='Поставщик'),
        ),
    ]
