# Generated by Django 5.0 on 2023-12-30 21:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronet', '0004_alter_company_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 30, 21, 35, 39, 873774, tzinfo=datetime.timezone.utc), null=True, verbose_name='Дата создания'),
        ),
    ]
