# Generated by Django 5.0 on 2023-12-30 21:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronet', '0005_alter_company_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 31, 0, 36, 17, 176542), null=True, verbose_name='Дата создания'),
        ),
    ]
